# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zAFu2-MnhgjFlwPFC2vwjKjIIYsL7UO_
"""

import streamlit as st
import joblib
from sklearn.feature_extraction.text import TfidfVectorizer

# Load the model and vectorizer
model = joblib.load('spam_classifier_nb.pkl')
vectorizer = joblib.load('tfidf_vectorizer.pkl')

# Function to predict spam or ham
def predict_email(email_text):
    email_vector = vectorizer.transform([email_text])
    prediction = model.predict(email_vector)
    return 'Spam' if prediction == 1 else 'Ham'

# Streamlit app
st.title('Spam Detection System')
st.write('Enter the email text below to classify it as Spam or Ham')

# Text input
email_text = st.text_area('Email Text')

if st.button('Predict'):
    if email_text:
        result = predict_email(email_text)
        st.write(f'The email is classified as: **{result}**')
    else:
        st.write('Please enter the email text')